version: "3"

services:
  cache:
    image: "redis"
    ports:
      - 6379:6379
  database:
    image: "postgres:latest"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

    # For logging queries in development only
    command: [ "postgres", "-c", "log_statement=all" ]